language: node_js
cache: yarn

after_success: npx codecov

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - yarn test
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
