language: node_js
node_js:
  - "lts/*"
cache: yarn

after_success: npx codecov

jobs:
  include:
    - script: yarn test:coverage

    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn publish
