version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
jobs:
  test:
    working_directory: ~/disputes
    docker:
      - image: circleci/node:12.10.0

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: test
          command: yarn test:ci
      - run:
          name: codecov
          command: npx codecov

workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - cypress/run:
          yarn: true
          record: true
          # we only run it in the front-end
          working_directory: apps/frontend
          start: yarn start:ci
          wait-on: "http://localhost:8080"
