version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  test:
    working_directory: ~/disputes
    docker:
      - image: circleci/node:11.13.0
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: disputes_test

    environment:
      DB_CONNECTION_STRING: "postgresql://postgres@localhost:5432/disputes_test?sslmode=disable"

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Setup test environment
          command: yarn setup:ci
      - run:
          name: test
          command: yarn test:ci
      - run:
          name: codecov
          command: npx codecov
      # persist workspace for the next command
      - persist_to_workspace:
          root: .
          paths: .

  publish:
    working_directory: ~/disputes
    docker:
      - image: circleci/node:11.13.0
    steps:
      - attach_workspace:
          at: ~/disputes
      - run:
          name: add github.com to ssh known_hosts
          command: "ssh-keyscan github.com >> ~/.ssh/known_hosts"

      - run:
          name: publish packages
          command: "yarn lerna publish --yes"

workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - cypress/run:
          yarn: true
          record: true
          # we only run these in the front-end atm
          working_directory: apps/frontend
          start: yarn start:ci
          wait-on: "http://localhost:8080"

      - publish:
          requires:
            - test
            - cypress/run
